apiVersion: v1
kind: ConfigMap
metadata:
  name: viti-network-policies-ssi-config
  namespace: {{ .Values.namespace | default "ssi" }}
data:
  config.yaml: |
    ---
    DENO_ENV: {{ .Values.settings.environment | quote }}
    SSI_NAME: "VITI-NETWORK-POLICIES-SSI"
    SSI_INTERVAL: {{ .Values.settings.interval | quote }}
    REQUEST_TIMEOUT: {{ .Values.settings.timeout | quote }}
    CRON_MODE: {{ .Values.settings.continuousMode | quote }}
    NAM_URL: {{ .Values.integration.nam.url | quote }}
    SPLUNK_URL: {{ .Values.integration.splunk.url | quote }}
    SPLUNK_INDEX: {{ .Values.integration.splunk.index | quote }}
    SPLUNK_SOURCE: {{ .Values.integration.splunk.source | quote }}
    SPLUNK_SOURCE_TYPE: "dcn-viti-network-policies-ssi"
