{{- if eq (lower (toString .Values.vault.enable)) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: viti-network-policies-ssi-secrets
  namespace: {{ .Values.namespace | default "ssi" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao				
    kind: ClusterSecretStore
  target:
    name: viti-network-policies-ssi-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: SPLUNK_TOKEN
      remoteRef:
        key: /viti-network-policies-ssi
        property: splunk-token
    - secretKey: NAM_TOKEN
      remoteRef:
        key: /viti-network-policies-ssi
        property: nam-token
{{- end }}