{{- if ne (lower (toString .Values.vault.enable)) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: viti-network-policies-ssi-secrets
  namespace: {{ .Values.namespace | default "ssi" }}
type: Opaque
stringData:
  secrets.yaml: |
    ---
    NAM_TOKEN: {{ .Values.credentials.namToken | quote }}
    SPLUNK_TOKEN: {{ .Values.credentials.splunkToken | quote }}
{{- end }}