
namespace: "ssi"
nameOverride: ""
image:
  repository: "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-viti-network-policies-ssi"
  tag: "latest"
  pullPolicy: "Always"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3
allowConcurrent: false

schedule: "*/15 * * * *"

limits:
  memory:
    min: "384Mi"
    max: "1152Mi"
  cpu:
    min: "300m"
    max: "600m"

settings:
  infrastructure: prod # prod, qa
  environment: production # Runtime environment: development, production
  interval: 300 # In seconds
  timeout: 3000 # In milliseconds
  continuousMode: false

integration:
  nam:
    url: ""
  ipam:
    url: ""
  splunk:
    enabled: true
    url: "https://splunk-hec.nhn.no"
    index: "dc_nam"
    source: "viti-network-policies-ssi:qa"
    token:
  
vault:
  enable: false

credentials:
  namToken: ""       # Property name within the secret to use as the token
  splunkToken: ""    # Property name within the secret to use as the token

workspace: dcn-viti-network-policies-ssi