schedule: "*/15 * * * *"

limits:
  memory:
    min: "384Mi"
    max: "1152Mi"
  cpu:
    min: "300m"
    max: "600m"

settings:
  environment: development
  infrastructure: qa
  interval: 300
  continuousMode: false

integration:
  nam:
    url: "https://qa.dcn.nhn.no:3000/api"
  splunk:
    url: "https://splunk-hec.nhn.no"
    index: "dc_nam"
    source: "viti-network-policies-ssi:qa"

credentials:
  namToken: "{{ .Values.credentials.namToken }}"
  splunkToken: "{{ .Values.credentials.splunkToken }}"

alarmathan:
  enable: true
  metadata:
    labels:
      release: kube-prometheus-stack
  labels:
    app: viti-network-policies-ssi
    environment: test
    cluster: mos3-k8s-qa-001
    criticality: Moderat
    severity: Høy
    service_id: 917
    team: Team Datasenter-Nettverk (Forretningsområde Skytjenester)
    varseltilos: test
    namespace: kube-prometheus-stack

workspace: viti-network-policies-ssi
